services:
  plextmdb:
    build: .
    container_name: plexitrack
    ports:
      - '5555:5555'
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data