version: '3'

services:
  plex-episode-tracker:
    build: .
    container_name: plex-episode-tracker
    ports:
      - "8080:8080"
    environment:
      - PLEX_URL=http://xxx.xxx.xxx.xxx
      - PLEX_TOKEN=xxxxxxx
      - PLEX_LIBRARY=TV Shows
      - TMDB_API_KEY=xxxxxxxxx
      - APP_PORT=8080
      - APP_DEBUG=true
      - APP_HOST=0.0.0.0
      - APP_SCAN_RESULTS_PATH=scan_results.json
    volumes:
      - ./scan_results.json:/app/scan_results.json
    restart: unless-stopped
